### ISSUE TITLE
Hi! some songs couldn't covert

### ISSUE THREAD

**Issue by iamcy** [magic-akari/ncmc#2]
songs list:

http://music.163.com/m/song?id=1302132211&userid=1151411
http://music.163.com/m/song?id=19526921&userid=1151411
http://music.163.com/m/song?id=18529562&userid=1151411

Error messages:
total: 1
--------------------------------
   1 <- C:\Users\isy\Desktop\ncmc-v0.1.6-x86_64-pc-windows-gnu\Can't Help Falling in Love - Kina Grannis.ncm

thread 'main' panicked at 'slice index starts at 22 but ends at 0', libcore\slice\mod.rs:2340:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by magic-akari** [comment]
Are you using the [latest version](https://github.com/magic-akari/ncmc/releases/latest)?

**Comment by magic-akari** [comment]
It's weird. It works on my macOS. I will test it on Windows tomorrow.

**Comment by iamcy** [comment]
yes

The download link is https://github.com/magic-akari/ncmc/releases/download/v0.1.6/ncmc-v0.1.6-x86_64-pc-windows-gnu.zip

macOS has same error. The version is
https://github.com/magic-akari/ncmc/releases/download/v0.1.6/ncmc-v0.1.6-x86_64-apple-darwin.tar.gz

**Comment by iamcy** [comment]
> tomorrow

thanks!

**Comment by magic-akari** [comment]
I noticed that the same song downloaded from macOS and downloaded from Windows is different. The hash changed.
From the error message you provided, it should be that the meta information of the song was lost. I have never seen this problem before. Could you share the ncm file?

**Comment by iamcy** [comment]
Thank you very much for your attention, I am very happy to share the files and send it to your github mailbox.

**Comment by iamcy** [comment]
Thanks again!
