### ISSUE TITLE
不要将工具信息写入到comment中

### ISSUE THREAD

**Issue by Reverier-Xu** [magic-akari/ncmc#44]
comment字段中有163 key，写入工具信息之后播放器就无法识别解码并和网易云的API集成了；而且ID3 v2标准中并没有规定可以使用分号分割不同的comment字段，这意味着所有播放器都是把comment当成普通字符串进行处理的。

![image](https://github.com/magic-akari/ncmc/assets/41937333/b517657e-e083-440d-900d-910992abb0a9)

或许可以考虑把 Convert by 写入到其他字段里？例如 https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2.2.html#involved-people-list 或者 Producer。

**Comment by magic-akari** [comment]
1. In FLAC, ID3 is not used; instead, metadata is managed through VorbisComment.
2. The comment does not use semicolons; the semicolons in your screenshot indicates how mpv represents multiple values.
3. You can verify using metaflac as shown in the figure below.

```
metaflac --list your.flac
```
<img width="729" alt="image" src="https://github.com/magic-akari/ncmc/assets/7829098/86554e24-f8c3-41cc-ab71-6dbc9fa240a0">
